version: '3'

services:
  api:
    build: .
    ports:
      - '3000'
    environment:
      - PORT=3000
    volumes:
      - '.:/app'
      - /app/node_modules
    command: npx nodemon start
    depends_on:
      - redis

  redis:
    image: redis:7.2.3
    ports:
      - '6379:6379'
